// <auto-generated>
// This file is generated automatically. Do not modify.
// </auto-generated>

namespace TelmanAchievements
{
    public enum AchievementId
    {
        TimeToGo,
        CuriosNose,
        CuriosNosefsd,
        fsdfsdfsf,
    }
}
