#if UNITY_EDITOR

using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace TelmanAchievements
{

    [CustomEditor(typeof(AchievementDatabase))]
    public class AchievementGeneratorEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();

            GUILayout.Space(15);

            AchievementDatabase database = (AchievementDatabase)target;

            bool isValid = Validate(database, out string error);

            if (!isValid)
            {
                EditorGUILayout.HelpBox(error, MessageType.Error);
            }

            GUI.enabled = isValid;

            if (GUILayout.Button("Generate Achievement Enum", GUILayout.Height(30)))
            {
                GenerateEnum(database);
            }

            GUI.enabled = true;
        }

        private static bool Validate(AchievementDatabase database, out string error)
        {
            error = null;

            if (database.Achievements == null || database.Achievements.Count == 0)
            {
                error = "Achievement list is empty.";
                return false;
            }

            HashSet<string> ids = new();

            for (int i = 0; i < database.Achievements.Count; i++)
            {
                AchievementDefinition achievement = database.Achievements[i];

                if (achievement == null)
                {
                    error = $"Achievement at index {i} is null.";
                    return false;
                }

                string id = achievement.Id;

                if (string.IsNullOrWhiteSpace(id))
                {
                    error = $"Achievement at index {i} has an empty ID.";
                    return false;
                }

                if (!Regex.IsMatch(id, @"^[A-Za-z_][A-Za-z0-9_]*$"))
                {
                    error = $"Invalid ID '{id}' at index {i}.\n\n" +
                            "ID must start with a letter or '_' and contain only letters, numbers and '_'.";
                    return false;
                }

                if (!ids.Add(id))
                {
                    error = $"Duplicate achievement ID: '{id}'.";
                    return false;
                }

                if (IsCSharpKeyword(id))
                {
                    error = $"ID '{id}' is a C# keyword and cannot be used as an enum value.";
                    return false;
                }
            }

            return true;
        }

        private static void GenerateEnum(AchievementDatabase database)
        {
            StringBuilder builder = new();

            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is generated automatically. Do not modify.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("namespace TelmanAchievements");
            builder.AppendLine("{");
            builder.AppendLine("    public enum AchievementId");
            builder.AppendLine("    {");

            foreach (AchievementDefinition achievement in database.Achievements)
            {
                builder.AppendLine($"        {achievement.Id},");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            string databasePath = AssetDatabase.GetAssetPath(database);
            string databaseDirectory = Path.GetDirectoryName(databasePath);

            string pluginRoot = GetPluginRoot(databaseDirectory);

            if (string.IsNullOrEmpty(pluginRoot))
            {
                Debug.LogError("Could not find TelmanAchievements root folder.");
                return;
            }

            string generatedDirectory = Path.Combine(
                pluginRoot,
                "Scripts",
                "Autogenerated"
            );

            Directory.CreateDirectory(generatedDirectory);

            string path = Path.Combine(
                generatedDirectory,
                "AchievementId.cs"
            );

            File.WriteAllText(path, builder.ToString());

            AssetDatabase.Refresh();

            Debug.Log($"Achievement enum generated: {path}");
        }

        private static string GetPluginRoot(string directory)
        {
            DirectoryInfo current = new(
                Path.GetFullPath(directory)
            );

            while (current != null)
            {
                if (current.Name == "TelmanAchievements")
                {
                    return current.FullName;
                }

                current = current.Parent;
            }

            return null;
        }

        private static bool IsCSharpKeyword(string value)
        {
            return value switch
            {
                "abstract" or
                "as" or
                "base" or
                "bool" or
                "break" or
                "byte" or
                "case" or
                "catch" or
                "char" or
                "checked" or
                "class" or
                "const" or
                "continue" or
                "decimal" or
                "default" or
                "delegate" or
                "do" or
                "double" or
                "else" or
                "enum" or
                "event" or
                "explicit" or
                "extern" or
                "false" or
                "finally" or
                "fixed" or
                "float" or
                "for" or
                "foreach" or
                "goto" or
                "if" or
                "implicit" or
                "in" or
                "int" or
                "interface" or
                "internal" or
                "is" or
                "lock" or
                "long" or
                "namespace" or
                "new" or
                "null" or
                "object" or
                "operator" or
                "out" or
                "override" or
                "params" or
                "private" or
                "protected" or
                "public" or
                "readonly" or
                "ref" or
                "return" or
                "sbyte" or
                "sealed" or
                "short" or
                "sizeof" or
                "stackalloc" or
                "static" or
                "string" or
                "struct" or
                "switch" or
                "this" or
                "throw" or
                "true" or
                "try" or
                "typeof" or
                "uint" or
                "ulong" or
                "unchecked" or
                "unsafe" or
                "ushort" or
                "using" or
                "virtual" or
                "void" or
                "volatile" or
                "while"
                    => true,

                _ => false
            };
        }
    }
}

#endif